version: "3.1"

services:
    rabbitmq:
        image: rabbitmq:3.8.2-management
        container_name: rabbitmq_tests
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "admin" # para a prova de integração contínua no senac, mas o certo seria usar .dotenv ...
            RABBITMQ_DEFAULT_PASS: "admin123" # para a prova de integração contínua no senac, mas o certo seria usar .dotenv ...
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq  # Persist data

volumes:
    rabbitmq_data: